package com.jordan.dijkstrasalgorithm.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jordan
 */
public class View extends javax.swing.JFrame {
    /*VentanaMatriz ventanaMatriz;
    InterfazGrafo interfazGrafo;
    Grafo grafo;
    private int vertices;*/

    public View() {
        initComponents();
        setLocationRelativeTo(null);
        lblScreen.setText("Seleccione una opción del menú principal.");
        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblScreen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 630));
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setPreferredSize(new java.awt.Dimension(1000, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        btn1.setForeground(new java.awt.Color(0, 0, 255));
        btn1.setText("1. Ingresar cantidad de vértices ");
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn1);
        btn1.setBounds(10, 80, 210, 30);

        btn2.setEnabled(false);
        btn2.setText("2. Crear matriz de adyacencia");
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn2);
        btn2.setBounds(10, 120, 210, 30);

        btn3.setEnabled(false);
        btn3.setText("3. Ingresar pesos de aristas");
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn3);
        btn3.setBounds(10, 160, 210, 30);

        btn4.setEnabled(false);
        btn4.setText("4. Establecer nodo de partida");
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn4);
        btn4.setBounds(10, 200, 210, 30);

        btn5.setEnabled(false);
        btn5.setText("5. Establecer nodo de llegada");
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn5);
        btn5.setBounds(10, 240, 210, 30);

        btn6.setEnabled(false);
        btn6.setText("6. Desplegar ruta más corta");
        btn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn6);
        btn6.setBounds(10, 280, 210, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(260, 10, 730, 388);

        btn7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(102, 102, 255));
        btn7.setText("Reiniciar");
        getContentPane().add(btn7);
        btn7.setBounds(40, 320, 160, 30);

        btn8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(102, 102, 255));
        btn8.setText("Salir");
        getContentPane().add(btn8);
        btn8.setBounds(40, 360, 160, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menú principal");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 210, 30);

        lblScreen.setBackground(new java.awt.Color(255, 255, 255));
        lblScreen.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lblScreen.setForeground(new java.awt.Color(51, 51, 255));
        lblScreen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblScreen.setMaximumSize(new java.awt.Dimension(450, 450));
        lblScreen.setPreferredSize(new java.awt.Dimension(450, 450));
        getContentPane().add(lblScreen);
        lblScreen.setBounds(260, 410, 730, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 630);
    }// </editor-fold>//GEN-END:initComponents
    
    public JLabel getJLabel1(){
        return lblScreen;
    }

    public JButton getBtn1() {
        return btn1;
    }

    public void setBtn1(JButton btn1) {
        this.btn1 = btn1;
    }

    public JButton getBtn2() {
        return btn2;
    }

    public void setBtn2(JButton btn2) {
        this.btn2 = btn2;
    }

    public JButton getBtn3() {
        return btn3;
    }

    public void setBtn3(JButton btn3) {
        this.btn3 = btn3;
    }

    public JButton getBtn4() {
        return btn4;
    }

    public void setBtn4(JButton btn4) {
        this.btn4 = btn4;
    }

    public JButton getBtn5() {
        return btn5;
    }

    public void setBtn5(JButton btn5) {
        this.btn5 = btn5;
    }

    public JButton getBtn6() {
        return btn6;
    }

    public void setBtn6(JButton btn6) {
        this.btn6 = btn6;
    }

    public JButton getBtn7() {
        return btn7;
    }

    public void setBtn7(JButton btn7) {
        this.btn7 = btn7;
    }

    public JButton getBtn8() {
        return btn8;
    }

    public void setBtn8(JButton btn8) {
        this.btn8 = btn8;
    }

    public JLabel getLblScreen() {
        return lblScreen;
    }

    public void setLblScreen(JLabel lblScreen) {
        this.lblScreen = lblScreen;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblScreen;
    // End of variables declaration//GEN-END:variables

}
